# this is the build file for project 
# it is autogenerated by the xmake build system.
# do not edit by hand.

ifneq ($(VERBOSE),1)
VV=@
endif

CU=/usr/bin/clang
MXX=/usr/bin/gcc
MM=/usr/bin/gcc
CXX=/usr/bin/gcc
AS=/usr/bin/gcc
RC=/usr/bin/rustc
CC=/usr/bin/gcc

AR=/usr/bin/ar
RCAR=/usr/bin/rustc
SH=/usr/bin/g++
RCSH=/usr/bin/rustc
LD=/usr/bin/g++
RCLD=/usr/bin/rustc

main_LD=/usr/bin/g++
main_CXX=/usr/bin/gcc
main_CXX=/usr/bin/gcc

main_CXXFLAGS=-m64 -I.
main_CXXFLAGS=-m64 -I.
main_LDFLAGS=-m64

default:  main

all:  main

.PHONY: default all  main

main: build/linux/x86_64/release/main
build/linux/x86_64/release/main: build/.objs/main/linux/x86_64/release/main.cpp.o build/.objs/main/linux/x86_64/release/Type/src/Object.cpp.o build/.objs/main/linux/x86_64/release/Type/src/Point.cpp.o build/.objs/main/linux/x86_64/release/Type/src/Position.cpp.o build/.objs/main/linux/x86_64/release/Screen/src/Screen.cpp.o
	@echo linking.release main
	@mkdir -p build/linux/x86_64/release
	$(VV)$(main_LD) -o build/linux/x86_64/release/main build/.objs/main/linux/x86_64/release/main.cpp.o build/.objs/main/linux/x86_64/release/Type/src/Object.cpp.o build/.objs/main/linux/x86_64/release/Type/src/Point.cpp.o build/.objs/main/linux/x86_64/release/Type/src/Position.cpp.o build/.objs/main/linux/x86_64/release/Screen/src/Screen.cpp.o $(main_LDFLAGS)

build/.objs/main/linux/x86_64/release/main.cpp.o: main.cpp
	@echo compiling.release main.cpp
	@mkdir -p build/.objs/main/linux/x86_64/release
	$(VV)$(main_CXX) -c $(main_CXXFLAGS) -o build/.objs/main/linux/x86_64/release/main.cpp.o main.cpp

build/.objs/main/linux/x86_64/release/Type/src/Object.cpp.o: Type/src/Object.cpp
	@echo compiling.release Type/src/Object.cpp
	@mkdir -p build/.objs/main/linux/x86_64/release/Type/src
	$(VV)$(main_CXX) -c $(main_CXXFLAGS) -o build/.objs/main/linux/x86_64/release/Type/src/Object.cpp.o Type/src/Object.cpp

build/.objs/main/linux/x86_64/release/Type/src/Point.cpp.o: Type/src/Point.cpp
	@echo compiling.release Type/src/Point.cpp
	@mkdir -p build/.objs/main/linux/x86_64/release/Type/src
	$(VV)$(main_CXX) -c $(main_CXXFLAGS) -o build/.objs/main/linux/x86_64/release/Type/src/Point.cpp.o Type/src/Point.cpp

build/.objs/main/linux/x86_64/release/Type/src/Position.cpp.o: Type/src/Position.cpp
	@echo compiling.release Type/src/Position.cpp
	@mkdir -p build/.objs/main/linux/x86_64/release/Type/src
	$(VV)$(main_CXX) -c $(main_CXXFLAGS) -o build/.objs/main/linux/x86_64/release/Type/src/Position.cpp.o Type/src/Position.cpp

build/.objs/main/linux/x86_64/release/Screen/src/Screen.cpp.o: Screen/src/Screen.cpp
	@echo compiling.release Screen/src/Screen.cpp
	@mkdir -p build/.objs/main/linux/x86_64/release/Screen/src
	$(VV)$(main_CXX) -c $(main_CXXFLAGS) -o build/.objs/main/linux/x86_64/release/Screen/src/Screen.cpp.o Screen/src/Screen.cpp

clean:  clean_main

clean_main: 
	@echo remove.release main
	@rm -rf build/linux/x86_64/release/main
	@echo remove.release main.sym
	@rm -rf build/linux/x86_64/release/main.sym
	@echo remove.release main.cpp.o
	@rm -rf build/.objs/main/linux/x86_64/release/main.cpp.o
	@echo remove.release Type/src/Object.cpp.o
	@rm -rf build/.objs/main/linux/x86_64/release/Type/src/Object.cpp.o
	@echo remove.release Type/src/Point.cpp.o
	@rm -rf build/.objs/main/linux/x86_64/release/Type/src/Point.cpp.o
	@echo remove.release Type/src/Position.cpp.o
	@rm -rf build/.objs/main/linux/x86_64/release/Type/src/Position.cpp.o
	@echo remove.release Screen/src/Screen.cpp.o
	@rm -rf build/.objs/main/linux/x86_64/release/Screen/src/Screen.cpp.o

